# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=elgg

script:
  - docker build -t demyx/"$DEMYX_REPOSITORY" .
  - docker-compose up -d
  - sleep 30
  - docker exec -t demyx_elgg sh -c "php vendor/bin/elgg-cli plugins:list --status all"

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
